import React, { useMemo } from 'react';
import { TrendingDown, TrendingUp } from 'lucide-react';
import { billTrendFor, seriesKey } from '../../../core/domain/billTrends';
import { formatCurrency } from '../../../core/domain/units';
import type { Bill, BillPayment } from '../../../core/domain/types';
import { TrendBars } from '../../../shared/components/TrendBars';
import { cn } from '../../../shared/lib/cn';

/**
 * What this bill has cost, period by period.
 *
 * A rising electricity trend should be visible at a glance (prompt0.md §9.6),
 * so the bars are proportional and the sentence above them is generated by
 * `billTrends.ts` — never written here, and never claimed when the history is
 * too short to support it.
 */

const monthLabel = (period: string): string => {
  const [year, month] = period.split('-');
  const date = new Date(Number(year), Number(month) - 1, 1);
  return new Intl.DateTimeFormat(undefined, { month: 'short', year: '2-digit' }).format(date);
};

const dayLabel = (iso: string): string =>
  new Intl.DateTimeFormat(undefined, { day: 'numeric', month: 'short', year: 'numeric' }).format(
    new Date(iso),
  );

export const BillHistory: React.FC<{
  bill: Bill;
  bills: Bill[];
  payments: BillPayment[];
  currency: string;
}> = ({ bill, bills, payments, currency }) => {
  const { points, trend } = useMemo(() => billTrendFor(bill, bills), [bill, bills]);

  const seriesPayments = useMemo(() => {
    const ids = new Set(bills.filter((b) => seriesKey(b) === seriesKey(bill)).map((b) => b.id));
    return payments
      .filter((payment) => ids.has(payment.billId))
      .sort((a, b) => b.paidAt.localeCompare(a.paidAt));
  }, [bill, bills, payments]);

  if (points.length === 0) {
    return (
      <p className="rounded-xl border border-dashed border-border px-3 py-4 text-center text-xs text-muted-foreground">
        No amount history yet. Once this bill has been paid a couple of times, its trend shows up
        here.
      </p>
    );
  }

  const TrendIcon = trend.direction === 'FALLING' ? TrendingDown : TrendingUp;

  return (
    <div className="space-y-4">
      <section aria-label="Amount history" className="space-y-2">
        {trend.headline && (
          <p
            className={cn(
              'flex items-center gap-1.5 text-xs font-medium',
              trend.direction === 'RISING' && 'text-status-warning',
              trend.direction === 'FALLING' && 'text-status-good',
              trend.direction === 'STEADY' && 'text-muted-foreground',
            )}
          >
            {trend.direction !== 'STEADY' && <TrendIcon size={13} aria-hidden />}
            {trend.headline}
          </p>
        )}

        <TrendBars
          points={points.map((point) => ({
            id: point.billId,
            label: monthLabel(point.period),
            value: point.amount,
            valueLabel: formatCurrency(point.amount, currency),
          }))}
        />
      </section>

      {seriesPayments.length > 0 && (
        <section aria-label="Payments" className="space-y-1.5">
          <h4 className="text-[0.6875rem] font-semibold uppercase tracking-wide text-muted-foreground">
            Payments
          </h4>
          <ul className="divide-y divide-border">
            {seriesPayments.slice(0, 8).map((payment) => (
              <li key={payment.id} className="flex items-center justify-between gap-3 py-1.5">
                <span className="text-xs text-foreground">{dayLabel(payment.paidAt)}</span>
                <span className="flex items-center gap-2">
                  <span className="text-[0.6875rem] text-muted-foreground">{payment.method}</span>
                  <span className="tabular text-xs font-medium text-foreground">
                    {formatCurrency(payment.amount, currency)}
                  </span>
                </span>
              </li>
            ))}
          </ul>
        </section>
      )}
    </div>
  );
};
